### ISSUE TITLE
PGS_Net is missing

### ISSUE THREAD

**Issue by xinsheng44** [x-coral/WDA#1]
Hello,

I've been exploring your repository. However, I noticed that the source code for PGS_Net seems to be missing from the current version of the repository.  If the source code will be made available in the future?

Thank you for your assistance and for the great work on this project!

**Comment by x-coral** [comment]
Hello,

Thank you for your attention to detail and for bringing this to our notice. PGS_Net is identical to WDA_Net_r. We have corrected this and the updated source code is now available in the repository.
